"""Airline IATA code → full name lookup."""
from __future__ import annotations

AIRLINES: dict[str, str] = {
    # North America
    "AA": "American Airlines",
    "DL": "Delta Air Lines",
    "UA": "United Airlines",
    "WN": "Southwest Airlines",
    "B6": "JetBlue Airways",
    "AS": "Alaska Airlines",
    "NK": "Spirit Airlines",
    "F9": "Frontier Airlines",
    "G4": "Allegiant Air",
    "SY": "Sun Country Airlines",
    "HA": "Hawaiian Airlines",
    "MX": "Breeze Airways",
    "AC": "Air Canada",
    "WS": "WestJet",
    "PD": "Porter Airlines",
    "AM": "Aeroméxico",
    "VB": "VivaAerobus",
    "Y4": "Volaris",
    # South America
    "LA": "LATAM Airlines",
    "G3": "Gol",
    "JJ": "LATAM Brasil",
    "AV": "Avianca",
    "CM": "Copa Airlines",
    "A3": "Aegean Airlines",
    # Europe
    "BA": "British Airways",
    "LH": "Lufthansa",
    "AF": "Air France",
    "KL": "KLM",
    "IB": "Iberia",
    "AZ": "ITA Airways",
    "LX": "Swiss International Air Lines",
    "OS": "Austrian Airlines",
    "SK": "SAS Scandinavian Airlines",
    "AY": "Finnair",
    "TP": "TAP Air Portugal",
    "VY": "Vueling",
    "VU": "Transavia France",
    "HV": "Transavia",
    "FR": "Ryanair",
    "U2": "easyJet",
    "W6": "Wizz Air",
    "EW": "Eurowings",
    "TK": "Turkish Airlines",
    "PC": "Pegasus Airlines",
    "EI": "Aer Lingus",
    "SN": "Brussels Airlines",
    "LO": "LOT Polish Airlines",
    "OK": "Czech Airlines",
    "FB": "Bulgaria Air",
    "RO": "TAROM",
    "YM": "Montenegro Airlines",
    "BT": "airBaltic",
    "OU": "Croatia Airlines",
    "JP": "Adria Airways",
    "PS": "Ukraine International Airlines",
    "SU": "Aeroflot",
    "S7": "S7 Airlines",
    "U6": "Ural Airlines",
    # Middle East
    "EK": "Emirates",
    "QR": "Qatar Airways",
    "EY": "Etihad Airways",
    "FZ": "flydubai",
    "G9": "Air Arabia",
    "GF": "Gulf Air",
    "SV": "Saudia",
    "WY": "Oman Air",
    "KU": "Kuwait Airways",
    "LY": "El Al",
    "RJ": "Royal Jordanian",
    "ME": "Middle East Airlines",
    "MS": "EgyptAir",
    # Africa
    "ET": "Ethiopian Airlines",
    "KQ": "Kenya Airways",
    "SA": "South African Airways",
    "AT": "Royal Air Maroc",
    "TC": "Air Tanzania",
    "WB": "RwandAir",
    # Asia Pacific
    "NH": "All Nippon Airways",
    "JL": "Japan Airlines",
    "KE": "Korean Air",
    "OZ": "Asiana Airlines",
    "CX": "Cathay Pacific",
    "SQ": "Singapore Airlines",
    "TG": "Thai Airways",
    "MH": "Malaysia Airlines",
    "GA": "Garuda Indonesia",
    "PR": "Philippine Airlines",
    "VN": "Vietnam Airlines",
    "CI": "China Airlines",
    "BR": "EVA Air",
    "CA": "Air China",
    "MU": "China Eastern",
    "CZ": "China Southern",
    "HX": "Hong Kong Airlines",
    "FD": "Thai AirAsia",
    "AK": "AirAsia",
    "QZ": "Indonesia AirAsia",
    "D7": "AirAsia X",
    "TR": "Scoot",
    "3K": "Jetstar Asia",
    "JQ": "Jetstar Airways",
    "VA": "Virgin Australia",
    "QF": "Qantas",
    "NZ": "Air New Zealand",
    "FJ": "Fiji Airways",
    "AI": "Air India",
    "UK": "Vistara",
    "6E": "IndiGo",
    "SG": "SpiceJet",
    "IX": "Air India Express",
    "PK": "Pakistan International",
    "PA": "Airblue",
    "UL": "SriLankan Airlines",
    "BG": "Biman Bangladesh",
    # Sandbox / test
    "ZZ": "Duffel Airways",
}


def get_airline_name(code: str, max_len: int = 20) -> str:
    """Return full airline name for a code, truncated to max_len. Falls back to code."""
    name = AIRLINES.get(code.upper(), code)
    if len(name) > max_len:
        name = name[: max_len - 1] + "…"
    return name
